# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20180803_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvstoreunit',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
