# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20180803_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvstoreunit',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
