# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_auto_20180803_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvStoreContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='tvstoreunit',
            name='deletion_date',
        ),
        migrations.AddField(
            model_name='tvstorecontact',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.TvStoreUnit', verbose_name='unit'),
        ),
    ]
