# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0007_auto_20180803_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvstorecontact',
            name='unit_serial_nr',
            field=models.CharField(default='0000-0000', editable=False, max_length=200, verbose_name='serial_nr'),
        ),
        migrations.AddField(
            model_name='tvstorecontact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tvstorecontact',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'in progress'), (1, 'completed'), (2, 'aborted'), (3, 'saved')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tvstoreunit',
            name='serial_nr',
            field=models.CharField(db_index=True, editable=False, max_length=200, unique=True, verbose_name='serial_nr'),
        ),
    ]
