# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_auto_20180803_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvstorecontact',
            name='js_attributes',
            field=models.TextField(blank=True, verbose_name='js_attributes'),
        ),
        migrations.AddField(
            model_name='tvstoreunit',
            name='js_attributes',
            field=models.TextField(blank=True, verbose_name='js_attributes'),
        ),
        migrations.AlterField(
            model_name='tvstoreunit',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
