# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_auto_20180803_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvstoreunit',
            name='serial_nr',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='serial_nr'),
        ),
    ]
