# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_auto_20180803_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvstorecontact',
            name='unit_serial_nr',
            field=models.CharField(default='0000-0000', editable=False, max_length=200, verbose_name='unit_serial_nr'),
        ),
    ]
