# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0013_auto_20180803_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvstorecontact',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'PING'), (1, 'CREATE'), (2, 'UPDATE'), (3, 'ALERT')], db_index=True, default=0),
        ),
    ]
