# Generated by Django 2.1 on 2018-08-16 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0015_tvstoreunit_ftp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvstorecontact',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm.TvStoreUnit', verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='tvstorecontact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tvstoreunit',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='tvstoreunit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
