# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvStoreUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('serial_nr', models.CharField(editable=False, max_length=200, unique=True, verbose_name='serial_nr')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deletion_date', models.DateTimeField(default=datetime.datetime(2028, 8, 2, 14, 58, 12, 724094, tzinfo=utc))),
            ],
        ),
    ]
